# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recycle Can' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recycle Can
pod “GoogleMaps”

  target 'Recycle CanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Recycle CanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
